name: origamistability
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - joblib
  - matplotlib
  - tqdm
  - scipy
  - pip:
      - pyyaml
      - pathlib
      - -e .

